apiVersion: v1
kind: Service
metadata:
  name: mycustom-service
spec:
  selector:
    app.kubernetes.io/name: myapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 49152
  externalIPs:
    - 198.51.100.32
