apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: registry.k8s.io/test-webserver
    name: new-container
    volumeMounts:
    - mountPath: /test-pd
      name: mytest-volume
  volumes:
  - name: mytest-volume
    hostPath:
      # directory location on host
      path: /data
      # this field is optional
      type: Directory
