apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: clone-of-pvc-1
    #namespace: myns
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: 5Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: claim1
