apiVersion: v1
kind: Service
metadata:
  name: web-nginx
  namespace: mynewdevweb
  labels:
    name: web-nginx
spec: 
  ports:
    - name: mystateport
      port: 80
  clusterIP: None
  selector:
     name: web-nginx
