apiVersion: v1
kind: Pod
metadata:
  name: mylivecustom
  namespace: mynewdevweb
  labels:
    env: dev
spec:
  
    containers:
      - name: mycustomdeplive
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
         - containerPort: 8080
        readinessProbe:
          tcpSocket:
             port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
             port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10

