apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: lmycustomprobes
    image: registry.k8s.io/liveness
    imagePullPolicy: IfNotPresent
    ports:
      - name: liveness-port
        containerPort: 80
        hostPort: 8080
    
    livenessProbe:
      httpGet:
        path: ./healthz
        port: liveness-port
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      failureThreshold: 10
      periodSeconds: 5
      terminationGracePeriodSeconds: 60
