apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
  labels: 
    env: dev
    app: loclapv
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      env: "dev"
    matchExpressions:
      - {key: app, operator: In, values: [localpv]}
