apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
  labels:
    env: dev
    app: localapp
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /home/ashok/mnt/ssd1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: env
          operator: In
          values:
          - dev
