apiVersion: v1
kind: Service
metadata:
  name: mynew-service
spec:
  selector:
    app.kubernetes.io/name: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  clusterIP: 10.0.0.20
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
