apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  labels:
    env: dev
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: env
    values:
    - dev
    
