apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mynewdevweb
  #namespace: ns1
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  dataSourceRef:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: new-snapshot-demo
    namespace: mynewdevweb
  volumeMode: Filesystem
